# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tviit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tviit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(editable=False, max_length=40, unique=True)),
                ('content', models.TextField(max_length=160)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tviit.models.PathAndRename('attachments/screen'))),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to=tviit.models.PathAndRename('attachments/thumbs'))),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tviit.Tviit')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tviit sender')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
