# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0002_auto_20160418_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.UUIDField(default=5520706097631774865061499197582426561L, editable=False, primary_key=True, serialize=False),
        ),
    ]
