# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0003_auto_20160418_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tviit',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.BigIntegerField(default=333476718354923706401967975444791110744L, editable=False, unique=True),
        ),
    ]
