# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0004_auto_20160418_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=85766646640987679074608980524577268832L, editable=False, max_length=40, unique=True),
        ),
    ]
