# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0005_auto_20160418_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tviit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/attachments/'),
        ),
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=114607965808821317487333706904189962493L, editable=False, max_length=40, unique=True),
        ),
    ]
