# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:13
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0006_auto_20160421_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviit',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/attachments'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=273315303277233162605784614578742237893L, editable=False, max_length=40, unique=True),
        ),
    ]
