# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import tviit.models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0007_auto_20160421_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tviit.models.PathAndRename('/media/attachments')),
        ),
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=284202814074865270349421554809284541244L, editable=False, max_length=40, unique=True),
        ),
    ]
