# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import tviit.models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0008_auto_20160421_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tviit.models.PathAndRename('attachments')),
        ),
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=123804711897693600907221668352255585165L, editable=False, max_length=40, unique=True),
        ),
    ]
