# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0009_auto_20160523_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=324580337496601477576339729023008125140L, editable=False, max_length=40, unique=True),
        ),
    ]
