# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0010_auto_20160523_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=230515942316164415698088974230134088549L, editable=False, max_length=40, unique=True),
        ),
    ]
