# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import tviit.models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0011_auto_20160523_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tviit',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=tviit.models.PathAndRename('thumbs')),
        ),
        migrations.AlterField(
            model_name='tviit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tviit.models.PathAndRename('attachments/screen')),
        ),
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=14524367127637539922975784708442147974L, editable=False, max_length=40, unique=True),
        ),
    ]
