# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0013_auto_20160523_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=178888473633047374757980421422028863154L, editable=False, max_length=40, unique=True),
        ),
    ]
