# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0014_auto_20160523_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=207577245532991658078622904079357153798L, editable=False, max_length=40, unique=True),
        ),
    ]
