# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0015_auto_20160523_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=181804027269294391702334209778231751923L, editable=False, max_length=40, unique=True),
        ),
    ]
