# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0016_auto_20160524_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tviit',
            name='uuid',
            field=models.CharField(default=193187900849466526262558426051933285310L, editable=False, max_length=40, unique=True),
        ),
    ]
