# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tviit', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=user_profile.models.PathAndRename(b'profiles/screen'))),
                ('location', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=user_profile.models.PathAndRename(b'profiles/thumbs'))),
                ('follows', models.ManyToManyField(blank=True, related_name='_userprofile_follows_+', to='user_profile.UserProfile')),
                ('likes', models.ManyToManyField(blank=True, to='tviit.Tviit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
