# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userprofile_follows_+', to='user_profile.UserProfile'),
        ),
    ]
