# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=b'media/profiles/thumb/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_follows_+', to='user_profile.UserProfile'),
        ),
    ]
