# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20160418_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=b'media/profiles/'),
        ),
    ]
