# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20160523_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=user_profile.models.PathAndRename(b'profiles/screen')),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=user_profile.models.PathAndRename(b'profiles/thumbs')),
        ),
    ]
