# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20160523_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
