# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('tviit', '0016_auto_20160524_1348'),
        ('user_profile', '0006_auto_20160523_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(blank=True, to='tviit.Tviit'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.PathAndRename(b'profiles/thumbs')),
        ),
    ]
