# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20160524_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.PathAndRename(b'profiles/screen')),
        ),
    ]
